import Head from 'next/head'
import BestDeal from '../components/HomeComponents/BestDeal/BestDeal'
import Header from '../components/HomeComponents/Header/Header'
import NavigationBar from '../components/SharedComponents/NavigationBar/NavigationBar'
import DiscoverFinancial from '../components/HomeComponents/DiscoverFinancial/DiscoverFinancial'
import Footer from '../components/SharedComponents/Footer/Footer'
import Subscribe from '../components/HomeComponents/Subscribe/Subscribe'
import PartnersAndInvestors from '../components/HomeComponents/PartnersAndInvestors/PartnersAndInvestors'



export default function Home() {

  return (
    <div >
      <Head>
        <title>Aamartaka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* ------------- */}
        <NavigationBar />
        <Header />
        <BestDeal />
        <DiscoverFinancial />
        <PartnersAndInvestors />
        <Subscribe />
        <Footer />
      </main>
    </div>
  )
}
