import Head from 'next/head'
import BestDeal from '../components/HomeComponents/BestDeal/BestDeal'
import Header from '../components/HomeComponents/Header/Header'
import NavigationBar from '../components/SharedComponents/NavigationBar/NavigationBar'
import DiscoverFinancial from '../components/HomeComponents/DiscoverFinancial/DiscoverFinancial'
import Footer from '../components/SharedComponents/Footer/Footer'
import Subscribe from '../components/HomeComponents/Subscribe/Subscribe'
import PartnersAndInvestors from '../components/HomeComponents/PartnersAndInvestors/PartnersAndInvestors'

import useMediaQuery from '../components/SharedComponents/useMediaQuery/useMediaQuery';
import MobileNav from '../components/MobileHomeComponents/MobileNav/MobileNav'
import MobileHeader from '../components/MobileHomeComponents/MobileHeader/MobileHeader'
import MobileBestDeal from '../components/MobileHomeComponents/MobileBestDeal/MobileBestDeal'



export default function Home() {
  const isMobile = useMediaQuery('(max-width: 600px)');

  return (
    <div >
      <Head>
        <title>Aamartaka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {isMobile &&
          <>
            <MobileNav />
            <MobileHeader />
            <MobileBestDeal />
          </>
        }
        {!isMobile &&
          <>
            <NavigationBar />
            <Header />
            <BestDeal />
            <DiscoverFinancial />
            <PartnersAndInvestors />
            <Subscribe />
            <Footer />
          </>
        }
      </main>
    </div>
  )
}
